'''
Problem

In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s.
'''

import time
start_time = time.time()

print start_time

DS = "CCACAAAACAGCTGGACGGTTATGGGTATTTTCTTGACTCACAGCCCCACTTTGAATCTATCGTAGAGCAAGACTAGATTGTCCCAACTGGCCCTGGATCACTGACTTTTGGGAATGATAATGCCAGCGCTAACCGAACACCAGGTGATTCTGGATTCCTCAGTAGCTGGCAAAAATCTAACGGTGTTCGCACCGCGCCAAGTCTGCATGTAGGTAGCCCAGAGCATGCGTAGCATAAGACCTACCTGATCGGTCAGGGAATTAAGTTGGCTATCTACATAGTACGAAGTCCCGAAGGGTACTGACGAGGTAGCATCAGCGTGACGCCAGGCTTCGGTATACAGTTTTAGGGTGTCTGACAAGTGAATTAATATCTGTAGTCAAACCGTGAGCTCGGATAATGGAAGAAGTGTTCCGGAGATAGCGGAGTGTCTAAGAACGACTACTGTAGGCAAGTTGGATTTCCACTTCAGATGCTGTATCTCCTACTTGATAATCAGGTGACAATATACAAATCCCTTGGTGGGTCTTGACCCGCTGTCCCAAGTGAGTTGGCTTATGAGTTGCTTGTCCACGTCCGATGACCCGGACAAGCCTGCTGCATTCATCCACTGACGAGCCTTCCTTGTCGTGGAGCCGATGGACATGTTTTTTCCAATGAACGAATTTCACAACCCACGAACTTACGCCCTAAGCCTTTCAATTTGCCCACTGTGTTGGGCCAGGATGCACGACGCGACCTGGGACGGCGCACAGCGCAGTACTAGAAGCGCTTATCGGGGTGTCTGAGATAGTGAGTATGGGACCCGGTAACTCATCAGAATCCCAGCTGCGTTTACGTATTATGCCGAGAGAGAAATACCTGCCCTCGTTATCGG"[::-1]

result = ""

for c in DS:
	if c == 'A': result += 'T'
	elif c == 'T': result += 'A'
	elif c == 'C': result += 'G'
	elif c == 'G': result += 'C'
	else:
		result += c

print result

print time.time()

elapsed_time = time.time() - start_time
print("Elapsed time",elapsed_time*1000,"millisecond")